import pygame

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
GRID_SIZE = 20
GRID_WIDTH = SCREEN_WIDTH // GRID_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // GRID_SIZE

BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

FPS = 10

MAX_INITIAL_SNAKE_SIZE = 10
MAX_SPEED = 5
MAX_DURATION = 10

DEFAULT_INITIAL_SNAKE_SIZE = 3
DEFAULT_SPEED = 3
DEFAULT_TIME_ATTACK_MINUTES = 2

FONT_SIZE = 36
TITLE_FONT_SIZE = 74
MENU_FONT_SIZE = 48
SETTINGS_FONT_SIZE = 60
INSTRUCTION_FONT_SIZE = 28
GAME_OVER_FONT_SIZE = 74
GAME_OVER_SMALL_FONT_SIZE = 32

PLAYER_1_KEYS = {
    pygame.K_w: (0, -1),
    pygame.K_s: (0, 1),
    pygame.K_a: (-1, 0),
    pygame.K_d: (1, 0)
}

PLAYER_2_KEYS = {
    pygame.K_UP: (0, -1),
    pygame.K_DOWN: (0, 1),
    pygame.K_LEFT: (-1, 0),
    pygame.K_RIGHT: (1, 0)
}